<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Foldara.Core/Foldara.Core.csproj" />
    <ProjectReference Include="../Foldara.Storage/Foldara.Storage.csproj" />
  </ItemGroup>
</Project>
